FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Miksu

Hello

## Hello friend [/hello]

### Says Hello to a friend [GET]

+ Response 200 (application/json)

        [
            {
                "response": "Hello friend!"
            }
        ]