FORMAT: 1A
HOST: http://140.86.1.231:3000

# Miksu

Hello

## Hello friend [/hello/{name}]

### Says Hello to a friend [GET]

+ Response 200 (application/json)

        {
            "response": "Hello friend!"
        }